void calc_addChar(char c);
void calc_on(void);
void calc_off(void);
void calc_del(void);
void calc_enter(void);
void calc_add(void);
void calc_divide(void);
void calc_multiply(void);
void calc_subtract(void);
void calc_modetoggle(void);
